### ISSUE TITLE
Saved file URI

### ISSUE THREAD

**Issue by antonfire** [Nexxa/cordova-base64-to-gallery#6] opened 2016-04-12 17:02 UTC
Any chance this could return the url of the saved file to the success callback? That would be really handy.

**Comment by bastian-meier** [comment] 2016-04-12 17:18
It does ...

`cordova.base64ToGallery(
                    base64,
                    '',
                    function (path) {
                    });`

Please provide your code if this Problem stil exists.

**Comment by StefanoMagrassi** [comment] 2016-04-12 17:39
Maybe it isn't so clear from the documentation... I will update it soon with a better example

**Comment by antonfire** [comment] 2016-04-12 19:06
Hi still not working, returns null (path is null), see...

```
            cordova.base64ToGallery(
                $scope.base64,

                'img_',

                function(msg){
                    console.log('path is '+msg);
                },

                function(err){
                    console.error(err);
                }
            );
```

Saves file to photos as expected but returns null as path. IOS 9.3.1

**Comment by StefanoMagrassi** [comment] 2016-04-13 07:25
@antonfire I think you're right: it seems there is a different implementation of what is returned between Android and the other 2 platforms.

As I wrote in the readme, this plugin is a fork of another project and I'm not a real mobile developer.

I think that aligning the 3 different implementation isn't so difficult, but I need time to better understand the fucking stupid objective-c syntax and test it on some real device

**Comment by StefanoMagrassi** [comment] 2016-04-13 08:39
According to the information I found (like [this](http://stackoverflow.com/questions/4457904/iphone-how-do-i-get-the-file-path-of-an-image-saved-with-uiimagewritetosavedpho)) the generated image path isn't available using `UIImageWriteToSavedPhotosAlbum` function.

The only data available are listed [here](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImage_Class/index.html#//apple_ref/doc/uid/TP40006890-CH3-SW19)...
I think that I cannot help you: the iOS code it's too tricky for me... 

The quick-n-dirty solution I can suggest you is to use the camera plugin to open the photo library and let the user select the image or, maybe, to try with the cordova file plugin...

**Comment by bastian-meier** [comment] 2016-04-13 10:22
`UIImageWriteToSavedPhotoAlbum` function just stores the imageData to the camera roll.

You need to convert it to NSData, than you can write it to an custom file path.
This path could then be returned.

I "blindcoded" this feature: [commit diff](https://github.com/bastian-meier/cordova-base64-to-gallery/commit/c87ced0adc71b4d3fbdccf49db49d9a4b878688a#diff-db3a269f6ff77398a212fa3fb3c1d9c2), but i cannot test it. My iOS device is broken :-(

@antonfire: could you check out my branch [link](https://github.com/bastian-meier/cordova-base64-to-gallery/tree/iosReturnPath) and test it ?

**Comment by antonfire** [comment] 2016-04-13 11:50
@bastian-meier There are 2 compile errors:
1. NSData\* imageData is redefined on line 31.
2. NSString\* timeString is referenced as timestring on line 40.

**Comment by bastian-meier** [comment] 2016-04-13 11:59
@antonfire 

this 2 bugs are fixed now, could you please re-test it.

**Comment by StefanoMagrassi** [comment] 2016-04-13 12:05
The path where to store the image has to be hardcoded in that manner or can be used a constant/method exposed by the OS?

**Comment by StefanoMagrassi** [comment] 2016-04-13 12:06
@bastian-meier , anyway, nice job.

When you feel confident, please send a PR

**Comment by bastian-meier** [comment] 2016-04-13 12:15
The path that i use is the standard path for the camera roll, i dont know if there is a way to recieve this path from the OS.

**Comment by StefanoMagrassi** [comment] 2016-04-13 12:30
Uhm maybe it could be useful to take a look into [cordova file plugin](https://github.com/apache/cordova-plugin-file/tree/master/src/ios).

Objective-c and iOS development really aren't my cup of tea...

**Comment by bastian-meier** [comment] 2016-04-13 12:42
my neither
reading objective-c-code already makes me headache
I could not find a method for getting the path from OS.

i will look into this later when i am at home.

**Comment by antonfire** [comment] 2016-04-13 12:46
Ok that returns the following:

/private/var/mobile/Media/DCIM/100APPLE/438114.873195.jpg

Just checking accessibility of the file, will report back.

**Comment by bastian-meier** [comment] 2016-04-13 12:51
that looks not too bad ...

**Comment by StefanoMagrassi** [comment] 2016-04-13 12:56
:+1:

**Comment by bastian-meier** [comment] 2016-04-13 13:34
@antonfire 
could you please test it again.
I added a check if the file could be created and just return the filePath on succes. Otherwise you should recieve an error.

**Comment by bastian-meier** [comment] 2016-04-13 14:09
I changed the traget file-path to documents inside of the app-folder.
This way i dont need static path-strings.

@antonfire 
please test it again, thanks

**Comment by antonfire** [comment] 2016-04-13 14:09
@bastian-meier thats saving to camera roll but returning path as null

**Comment by antonfire** [comment] 2016-04-13 14:10
@bastian-meier will that save to camera roll still?

**Comment by antonfire** [comment] 2016-04-13 14:11
@bastian-meier my reply 'thats saving to camera roll but returning path as null' was referring to not your most recent mod

**Comment by bastian-meier** [comment] 2016-04-13 14:12
@antonfire give me a second ...

**Comment by StefanoMagrassi** [comment] 2016-04-13 14:13
@bastian-meier wouldn't be better to use [UIImagePNGRepresentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/#//apple_ref/c/func/UIImagePNGRepresentation) instead of UIImageJPEGRepresentation?

The plugin was designed to save png files.

**Comment by bastian-meier** [comment] 2016-04-13 14:24
@antonfire
 i think you are right, if added to documents folder, the image would not be added to camera roll, i use the static path again for now

@StefanoMagrassi 
changed it to png

@antonfire 
could you please test again, i am sorry that i cant test it by myself, i think i need a new ios device :-)

**Comment by StefanoMagrassi** [comment] 2016-04-13 14:29
:+1: 

I hope that the static path won't cause issues in the future, but now we can't do differently

**Comment by antonfire** [comment] 2016-04-13 14:33
@bastian-meier 

There's a compile error, need to change:

[pngImageData writeToFile:imagePath atomically:NO]

to:

[pngImageData writeToFile:imagePath atomically:NO];

**Comment by bastian-meier** [comment] 2016-04-13 14:41
sorry for the typo.

i commited the fix, please test it again @antonfire

**Comment by antonfire** [comment] 2016-04-13 14:48
@bastian-meier Yes that's ok now, returning:

/private/var/mobile/Media/DCIM/100APPLE/445710.645266.png

I am assuming that to access the file the url will be:

file:///var/mobile/Media/DCIM/100APPLE/445710.645266.png

Is that right?

Thanks

**Comment by bastian-meier** [comment] 2016-04-13 15:03
yes, i think you are right, can you access the image with this url?

Is the Image added to camera roll? 

I changed the returned path to /var/mobile/Media/DCIM/100APPLE/xxxx.png

I will not add file:// because the android code does not add it too.

So you have to use it like that: 

```
cordova.base64ToGallery( 
  base64, 
  {}, 
  function (path) {
    image.src = 'file://' + path}
);
```

**Comment by antonfire** [comment] 2016-04-13 15:09
@bastian-meier 

Ok I will test and see if that works.

There may be an issue with DCIM/100APPLE as a destination, as I understand OS uses many DCIM/XXXAPPLE folders (101,102,103 etc) to handle file storage, not sure if this will cause problems by leapfrogging any allocation logic. Just a thought. See... https://discussions.apple.com/docs/DOC-8611

**Comment by antonfire** [comment] 2016-04-13 16:38
@bastian-meier I can't get anything from the url in the following formats:

file:///private/var/mobile/Media/DCIM/100APPLE/449839.482419.png
file:///var/mobile/Media/DCIM/100APPLE/449839.482419.png

Very odd.

**Comment by bastian-meier** [comment] 2016-04-13 19:17
There is a new commit.

I decided to store the image in documents folder (the image should than be accesable for your app).
If you set options.mediaScanner to true the saved Image will then be added to camera roll.

You can now use the options-object for setting a fileName-prefix and mediaScanner for adding the Image to the camera roll:

```
cordova.base64ToGallery( 
  base64, 
  {
    prefix: 'img_',
    mediaScanner: false
  }, 
  function (path) {
    image.src = 'file://' + path}
);
```

thats a lot of changes without a device for testing, @antonfire if you like you could test it.
If you dont want to test, its also OK.
I will test it with my new iPhone next week.

If you test it, please test it with mediaScanner: false and with mediaScanner: true

**Comment by antonfire** [comment] 2016-04-20 14:41
@bastian-meier Hi sorry I'd not seen your message, I have just tested and it produces a warning saying undeclared selector savedImage:wasSavedToPhotoAlbumWithError:contextInfo:, this becomes an error and crashes the app when the code is executed. Happy to test revisions. Cheers

**Comment by bastian-meier** [comment] 2016-04-20 14:47
@antonfire 

i did some testing a few days ago, it it working with options.mediaScanner = false.
There is the bug you found when mediaScanner = true.

The Plugin returns the path to the image and it could be used (i moved it by file-api in the image-folder of my app).

When i find some time i try to fix the mediaScanner part.

thanks for your Feedback

**Comment by bastian-meier** [comment] 2016-04-20 14:53
@antonfire 

i think i found the error, if you lik, you could test it again.

**Comment by antonfire** [comment] 2016-04-20 15:00
Is CDV success function being passed a non string value? It's clanging on:
- (CDVPluginResult_)resultWithStatus:(CDVCommandStatus)statusOrdinal messageAsString:(NSString_)theMessage

**Comment by antonfire** [comment] 2016-04-20 16:15
Is self.imagePath being passed into (void)savedImage? Just thinking aloud here.

**Comment by bastian-meier** [comment] 2016-05-02 10:52
Sorry for the long delay,

i fixed the bug, it works now with mediaScanner = true
@antonfire: could you please check if it works for you too.

I created a PR, i think @StefanoMagrassi will merge it when you confirm that it works.

thanks for your patience

**Comment by StefanoMagrassi** [comment] 2016-05-02 18:26
:+1:  

As soon as the test is ok, I'll merge the PR and publish the new version of the plugin

**Comment by antonfire** [comment] 2016-05-04 07:44
@bastian-meier Thanks, tested and can confirm it works perfectly. Great work, much appreciated!

**Comment by bastian-meier** [comment] 2016-05-05 15:42
@StefanoMagrassi  You can change documentation for options.prefix because i implemented (and you merged) this feature on ios too.

**Comment by StefanoMagrassi** [comment] 2016-05-05 15:45
@bastian-meier options.mediaScanner?

Check out the repo/readme: I update it a couple of minutes ago.

The new plugin's version [is on npm](https://www.npmjs.com/package/cordova-base64-to-gallery)

**Comment by bastian-meier** [comment] 2016-05-05 15:48
No, options.prefix 

In the documentation you say prefix just work on android and win, but it works on ios too

**Comment by StefanoMagrassi** [comment] 2016-05-05 15:53
@bastian-meier done!

Issue closed

**Comment by antonfire** [comment] 2016-05-05 15:53
@bastian-meier could I suggest the following as not all requirements are best suited to png...

```
function onDeviceReady() {
    cordova.base64ToGallery(
        base64Data,

        {
            prefix: 'img_',
            mediaScanner: true,
            mediaType: "to be populated by jpg/png"
        },

        function(msg) {
            console.log(msg);
        },

        function(err) {
            console.error(err);
        }
    );
}
```

Just thinking that this will be better to give the user a choice depending on media type and best fit for minimal data transfer in mobile use. 

I can do a PR for this if you don't have time.

Regards

Anthony

**Closed as completed by StefanoMagrassi** 2016-05-05 15:53 UTC
Labels: enhancement, ios, documentation

**Comment by StefanoMagrassi** [comment] 2016-05-05 15:55
@antonfire please open a new issue.

**Comment by agomezmoron** [comment] 2016-05-09 07:49
Hi,

In the fork I developed with a fork of yours (https://github.com/agomezmoron/cordova-save-image-gallery) it's supported.

Thanks

**Comment by StefanoMagrassi** [comment] 2016-05-17 15:14
@agomezmoron I read very quickly your code and seems to be very good.

I'm a bit overwhelmed by work now and with 0 time for development. --> #8

**Comment by antonfire** [comment] 2016-06-02 08:32
@bastian-meier Does this code store the image in the documents directory as well as the camera roll? Just wondering if this will allow iOS to conduct cleaning as isn't this just restricted to the temp folder? Will this cause bloat in the app directory if iOS can't clean it out? Cheers
